kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "homu"
  labels:
    app: homu
spec:
  runPolicy: "Serial" 
  triggers: 
    - type: "ImageChange"
  source: 
    type: "Git"
    git:
      uri: "https://github.com/cgwalters/projectatomic-ci-infra"
    contextDir: homu
  strategy: 
    type: "Docker"
    dockerStrategy:
      noCache: true
  output: 
    to:
      kind: "ImageStreamTag"
      name: "homu:latest"
