apiVersion: v1
kind: DeploymentConfig
metadata:
  name: homu
  labels:
    app: homu
spec:
  replicas: 1
  selector:
    app: homu
    deploymentconfig: homu
  template:
    metadata:
      labels:
        app: homu
        deploymentconfig: homu
    spec:
      containers:
        - image: homu
          name: homu
          ports:
            - containerPort: 8080
              name: homu
              protocol: TCP
          volumeMounts:
            - name: cfg
              mountPath: /etc/homu-secrets
              readOnly: true
            - name: sshcfg
              mountPath: /etc/homu-cfg
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: homu
      volumes:
        - name: cfg
          secret:
            secretName: homu-cfg
        - name: sshcfg
          configMap:
            name: homu-ssh-config
  triggers:
  - type: ConfigChange 
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
        - homu
      from:
        kind: ImageStreamTag
        name: homu:latest
    type: ImageChange  
  strategy:
    type: Rolling       
