apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: Service
  metadata:
    name: homu
    labels:
      app: homu 
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: homu
      deploymentconfig: homu

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: homu
    name: homu
  spec:
    to:
      name: homu
    port:
      targetPort: 8080
  tls:
    termination: edge
